[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SpotFormer"
authors = [{name = "Xilin Dang", email = "xldang23@cse.cuhk.edu.hk"}]
dynamic = ["version", "description"]
